apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopnow-frontend
  namespace: argocd
spec:
  destination:
    namespace: shopnow
    server: https://kubernetes.default.svc
  source:
    path: shopnow-frontend-chart
    repoURL: https://github.com/tranvix0910/shopnow-frontend.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
        - ../shopnow-frontend-config/overlays/production/values.yaml
      values: |
        image:
          repository: "022499043310.dkr.ecr.ap-southeast-1.amazonaws.com/shopnow/shopnow-frontend"
  project: shopnow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true