ingress:
  certificateArn: "arn:aws:acm:ap-southeast-1:022499043310:certificate/647360bb-b2ea-4ec5-9551-2da20236dd16"
  subnets: "subnet-00502d28cf8623a99,subnet-00f29dc65958e83c4,subnet-0b4dd832c80661a42"
  listenPorts: '[{"HTTP": 80}, {"HTTPS":443}]'
  groupName: "shopnow"
  actionsSslRedirect: '{"Type": "redirect", "RedirectConfig": {"Protocol": "HTTPS", "Port": "443", "Host": "#{host}", "Path": "/#{path}", "Query": "#{query}", "StatusCode": "HTTP_301"}}' 
