# Global settings
global:
  appName: "shopnow-frontend"
  namespace: "shopnow"
  environment: "production"  # dev, staging, production
  enabledComponents:
    configmap: false
    service: true
    ingress: true

# Deployment
image:
  repository: ""
  tag: "v1"
  pullPolicy: IfNotPresent

replicaCount: 1
rollingUpdate:
  maxSurge: 25%
  maxUnavailable: 25%

# Service
service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Ingress
ingress:
  className: "alb"
  host: "shopnow.tranvix.click"
  path: "/"
  pathType: Prefix
  certificateArn: ""  # Will be overridden by external secret
  subnets: ""         # Will be overridden by external secret
  listenPorts: ""     # Will be overridden by external secret
  groupName: ""       # Will be overridden by external secret
  actionsSslRedirect: ""  # Will be overridden by external secret

# ConfigMap
configmap:
  data: {}
  # Example:
  # data:
  #   application.properties: |
  #     server.port=8080
  #     spring.datasource.url=jdbc:mysql://db-service:3306/mydb

serviceAccount:
  create: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80