apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.appName }}-deployment
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.appName }}
    spec:
      containers:
        - name: {{ .Values.global.appName }}
          {{- if .Values.image.repository }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          {{- if .Values.global.enabledComponents.configmap }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/src/main/resources/application.properties
          {{- end }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      {{- if .Values.global.enabledComponents.configmap }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.global.appName }}-configmap
      {{- end }}
